name: folio
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2  # HTTP package to make API requests
  json_annotation: ^4.6.0  # Optional: For parsing JSON (if needed)
  flutter_html: ^3.0.0-beta.2 
  win32: ^5.5.5
  html: ^0.15.0  # Correctly indented
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  firebase_storage: ^12.3.0
  url_launcher: ^6.3.0
  flutter_pw_validator: ^1.6.0
  zego_uikit_prebuilt_call: ^4.16.5
  intl: ^0.17.0
  provider: ^6.0.0
  flutter_secure_storage: ^9.2.2
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/1024.png"
  adaptive_icon_foreground: "assets/images/1024.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # Add custom fonts here
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
