// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtMrSILxOhSct6HOB8DSCIVzZuxyR540g',
    appId: '1:866432989267:web:76dccc34dc3e81f0d56ea6',
    messagingSenderId: '866432989267',
    projectId: 'folio-29339',
    authDomain: 'folio-29339.firebaseapp.com',
    databaseURL: 'https://folio-29339-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'folio-29339.appspot.com',
    measurementId: 'G-QG7H7NTKPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD08AQh_ozf3QSFAZcg7eTWGtBMJw_kG_0',
    appId: '1:866432989267:android:57f897cf2489c0a5d56ea6',
    messagingSenderId: '866432989267',
    projectId: 'folio-29339',
    databaseURL: 'https://folio-29339-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'folio-29339.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrznpxbXv22Dp-nlioHu7EC7Ui8Tjumew',
    appId: '1:866432989267:ios:5e57bbd7e065e084d56ea6',
    messagingSenderId: '866432989267',
    projectId: 'folio-29339',
    databaseURL: 'https://folio-29339-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'folio-29339.appspot.com',
    iosBundleId: 'com.example.folio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrznpxbXv22Dp-nlioHu7EC7Ui8Tjumew',
    appId: '1:866432989267:ios:5e57bbd7e065e084d56ea6',
    messagingSenderId: '866432989267',
    projectId: 'folio-29339',
    databaseURL: 'https://folio-29339-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'folio-29339.appspot.com',
    iosBundleId: 'com.example.folio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtMrSILxOhSct6HOB8DSCIVzZuxyR540g',
    appId: '1:866432989267:web:20ed68bcc81af42cd56ea6',
    messagingSenderId: '866432989267',
    projectId: 'folio-29339',
    authDomain: 'folio-29339.firebaseapp.com',
    databaseURL: 'https://folio-29339-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'folio-29339.appspot.com',
    measurementId: 'G-PQ0V72VPWV',
  );
}
