import 'package:cloud_firestore/cloud_firestore.dart'; // Import Firestore
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:folio/firebase_options.dart'; // Import the generated firebase_options.dart
import 'package:folio/screens/homePage.dart';
import 'package:folio/screens/login.dart';
import 'package:folio/screens/splash.dart';
import 'package:folio/services/ClubListener.dart';
import 'package:folio/services/local.notifications.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions
        .currentPlatform, // Use the default Firebase options generated by flutterfire_cli
  );
  await LocalNotificationService.init(); // Initialize local notifications
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  User? user;
  late ClubListener _clubListener;
  bool isBanned = false; // Track if the user is banned
  late Stream<DocumentSnapshot<Map<String, dynamic>>>? bannedStream;

  @override
  void initState() {
    super.initState();
    user = FirebaseAuth.instance.currentUser; // Get the current user
    _clubListener = ClubListener(); // Initialize club listener
    if (user != null) {
      // Set up the real-time listener for banned status
      bannedStream = FirebaseFirestore.instance
          .collection('reader')
          .doc(user!.uid)
          .snapshots();
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFFF790AD)),
        useMaterial3: true,
        fontFamily: 'YoungSerif-Regular',
      ),
      home: user == null
          ? const Splash() // If user is not logged in, show Splash screen
          : StreamBuilder<DocumentSnapshot<Map<String, dynamic>>>(
              stream: bannedStream,
              builder: (context, snapshot) {
                if (snapshot.hasData) {
                  final data = snapshot.data?.data();
                  if (data != null && data['banned'] == true) {
                    return BannedMessagePage(); // Show banned message if user is banned
                  }
                  return HomePage(
                      userId: user!.uid); // Show HomePage if user is not banned
                } else if (snapshot.hasError) {
                  return const Center(
                    child: Text(
                      'Error loading data. Please try again.',
                      style: TextStyle(color: Colors.red),
                    ),
                  );
                }
                return const Center(
                    child:
                        CircularProgressIndicator()); // Show loading indicator while fetching data
              },
            ),
    );
  }
}

// Create a new page to display the banned message
class BannedMessagePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF8F8F3),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(20.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Text(
                'Your account has been suspended.',
                style: TextStyle(
                    fontSize: 20,
                    fontWeight: FontWeight.bold,
                    color: Colors.red),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 20),
              const Text(
                'Please contact Follio@gmail.com for assistance.',
                style: TextStyle(fontSize: 16, color: Colors.black54),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 40),
              ElevatedButton(
                onPressed: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(builder: (context) => const LoginPage()),
                  );
                },
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFFF790AD), // Background color
                  foregroundColor: Colors.white, // Text color
                  padding: const EdgeInsets.symmetric(
                      horizontal: 32.0, vertical: 16.0),
                  textStyle: const TextStyle(fontSize: 18),
                ),
                child: const Text('Exit'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
